#SET SQL_SAFE_UPDATES = 0;

#UPDATE EXE_RESULTS.RESULTS SET optimal_cardinality = JSON_LENGTH(optimal_solution);



#DELETE FROM EXE_RESULTS.RESULTS WHERE ID in ('34900');
#ALTER TABLE EXE_RESULTS.RESULTS ADD COLUMN optimal_value FLOAT;
#UPDATE EXE_RESULTS.RESULTS SET search_strategy = 'P';



#DESCRIBE EXE_RESULTS.RESULTS optimal_solution;
ALTER TABLE EXE_RESULTS.RESULTS MODIFY pruner VARCHAR(10);

#ALTER TABLE EXE_RESULTS.RESULTS DROP COLUMN kernel_remainder;

#DELETE FROM EXE_RESULTS.RESULTS WHERE file_name like '%3_5_15%' and id=0;

#ALTER TABLE EXE_RESULTS.RESULTS ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

#DELETE FROM EXE_RESULTS.RESULTS where search_strategy like 'V';

#ALTER TABLE EXE_RESULTS.RESULTS ADD COLUMN optimal_cardinality INT;

#DELETE FROM EXE_RESULTS.RESULTS where filename like '%3_5_15/srs_165%';